name: torch4p
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python=3.7.1
  - pytorch=1.4.0
  - torchvision=0.5.0
  - mkl==2019.1
  - mkl-include==2019.1
  - tqdm==4.45.0
  - visdom==0.1.8.9
  - pandas==1.0.3
  - tabulate==0.8.7
  - redis-py==3.5.3
  - black==19.10b0
  - pylint==2.4.4
  - pip==20.0.2
  - pip:
    - Flask==1.1.1
    - Flask-Cors==3.0.7
    - Flask-Sockets==0.2.1
    - flask_login==0.5.0
    - syft==0.2.6
